export const ADD_BIKE = 'ADD_BIKE';
export const ADD_COMPONENT = 'ADD_COMPONENT';
export const SET_ACTIVE_BIKE = 'SET_ACTIVE_BIKE';
export const ADD_BIKE_DISTANCE = 'ADD_BIKE_DISTANCE';
export const SET_DISTANCE_ALERT = 'SET_DISTANCE_ALERT';
export const DISABLE_SERVICE_ALERT = 'DISABLE_DISTANCE_ALERT';
export const UPDATE_COMPONENTS_DISTANCE = 'UPDATE_COMPONENTS_DISTANCE';
