export const ADD_BIKE = 'ADD_BIKE';
export const ADD_COMPONENT = 'ADD_COMPONENT';
export const SET_ACTIVE_BIKE = 'SET_ACTIVE_BIKE';
export const ADD_BIKE_DISTANCE = 'ADD_BIKE_DISTANCE';

export const SET_DISTANCE_ALERT = 'SET_DISTANCE_ALERT';
export const DISABLE_SERVICE_ALERT = 'DISABLE_DISTANCE_ALERT';
export const UPDATE_COMPONENTS_DISTANCE = 'UPDATE_COMPONENTS_DISTANCE';
export const SWITCH_TO_BIKE = 'SWITCH_TO_BIKE';
export const RETIRE_COMPONENT = 'RETIRE_COMPONENT';
export const DELETE_COMPONENT = 'DELETE_COMPONENT';

export const OPEN_CONFIRM_DIALOG = 'OPEN_CONFIRM_DIALOG';
export const CLOSE_CONFIRM_DIALOG = 'CLOSE_CONFIRM_DIALOG';
