export const ADD_BIKE = 'ADD_BIKE';
export const EDIT_BIKE = 'EDIT_BIKE';
export const SET_ACTIVE_BIKE = 'SET_ACTIVE_BIKE';
export const UPDATE_BIKE_DISTANCE = 'UPDATE_BIKE_DISTANCE';
export const RETIRE_BIKE = 'RETIRE_BIKE';
export const DELETE_BIKE = 'DELETE_BIKE';

export const ADD_COMPONENT = 'ADD_COMPONENT';
export const EDIT_COMPONENT = 'EDIT_COMPONENT';
export const SET_DISTANCE_ALERT = 'SET_DISTANCE_ALERT';
export const DISABLE_SERVICE_ALERT = 'DISABLE_DISTANCE_ALERT';
export const UPDATE_COMPONENTS_DISTANCE = 'UPDATE_COMPONENTS_DISTANCE';
export const SWITCH_TO_BIKE = 'SWITCH_TO_BIKE';
export const RETIRE_COMPONENT = 'RETIRE_COMPONENT';
export const RETIRE_COMPONENTS = 'RETIRE_COMPONENTS';
export const DELETE_COMPONENT = 'DELETE_COMPONENT';
export const DELETE_COMPONENTS = 'DELETE_COMPONENTS';

export const OPEN_CONFIRM_DIALOG = 'OPEN_CONFIRM_DIALOG';
export const CLOSE_CONFIRM_DIALOG = 'CLOSE_CONFIRM_DIALOG';

export const STRAVA_SYNC_START = 'STRAVA_SYNC_START';
export const STRAVA_SYNC_END = 'STRAVA_SYNC_END';
export const STRAVA_UPDATE_ATHLETE = 'STRAVA_UPDATE_ATHLETE';
export const STRAVA_UPDATE_BIKES = 'STRAVA_UPDATE_BIKES';
export const STRAVA_UPDATE_AUTH = 'STRAVA_UPDATE_AUTH';
export const STRAVA_SYNC_FAILED = 'STRAVA_SYNC_FAILED';
export const STRAVA_UPDATE_SYNC = 'STRAVA_UPDATE_SYNC';
export const STRAVA_GET_ATHLETE = 'STRAVA_GET_ATHLETE';
export const STRAVA_GET_GEAR = 'STRAVA_GET_GEAR';

export const ADD_ACTIVITIES = 'ADD_ACTIVITIES';
export const ADD_ACTIVITY = 'ADD_ACTIVITY';
export const EDIT_ACTIVITY = 'EDIT_ACTIVITY';
export const REMOVE_ACTIVITY = 'REMOVE_ACTIVITY';
export const REMOVE_ACTIVITIES = 'REMOVE_ACTIVITIES';
